# Generated by Django 3.2.3 on 2021-05-17 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Please enter the adventure's title", max_length=200)),
                ('dm_name', models.CharField(help_text='Please enter your name or a display name', max_length=200)),
                ('teaser', models.CharField(help_text='Please enter the teaser for the adventure', max_length=2000)),
                ('is_dnd5', models.BooleanField(help_text='Is this a D&D5 adventure?')),
                ('min_level', models.IntegerField(help_text='What is the minimum character level for this adventure?')),
                ('max_level', models.IntegerField(help_text='What is the maximum character level for this adventure?')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Please enter the name so we can know you', max_length=200)),
                ('adventure', models.ForeignKey(help_text='Which adventure do you want to play?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='view_tables.adventure')),
            ],
        ),
    ]
