# Generated by Django 3.2.3 on 2021-05-17 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adventure',
            name='teaser',
            field=models.TextField(help_text='Please enter the teaser for the adventure', max_length=2000),
        ),
    ]
