# Generated by Django 3.2.3 on 2021-05-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_tables', '0002_alter_adventure_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='max_number_of_players',
            field=models.IntegerField(default=5, help_text='Total numbers of players you are willing to host'),
        ),
    ]
