# Generated by Django 3.2.3 on 2021-05-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view_tables', '0003_adventure_max_number_of_players'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adventure',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='registrant',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='adventure',
            name='max_number_of_players',
            field=models.IntegerField(help_text='Total numbers of players you are willing to host'),
        ),
    ]
